name=CocoLinx EG800AK AT Parser Library
version=1.0.0
author=CocoLinx
maintainer=CocoLinx <info@cocolinx.com>
sentence=AT command parser library for CocoLinx EG800AK
paragraph=This library provides APIs for modem information, LTE connection, UDP, TCP, MQTT and date/time functions.
category=Communication
url=https://github.com/cocolinx/eg800ak-at-parser
architectures=*